import { Platform, StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#F7F4EE' },
  page: { padding: 20, gap: 16, paddingBottom: 28, zIndex: 1 },
  centered: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  centerText: { textAlign: 'center' },
  dashboardHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', minHeight: 72 },
  dashboardHeaderText: { flex: 1, paddingRight: 16 },
  brand: { fontSize: 22, fontWeight: '800', color: '#173A2A' },
  welcomeText: { color: '#6A776F', fontSize: 14, fontWeight: '600', marginTop: 4 },
  eyebrow: { color: '#2E7D58', fontWeight: '800', letterSpacing: 1.2, fontSize: 12, marginTop: 8 },
  title: { fontSize: 25, lineHeight: 36, fontWeight: '800', color: '#17211C', justifyContent: 'center' },
  body: { fontSize: 16, lineHeight: 24, color: '#405047' },
  syncBanner: { backgroundColor: '#E5F2EA', borderRadius: 14, borderWidth: 1, borderColor: '#B8D6C5', padding: 12 },
  syncBannerSaving: { backgroundColor: '#FFF5D9', borderColor: '#E8CA79' },
  syncBannerError: { backgroundColor: '#FCE1E1', borderColor: '#E7AAAA' },
  syncBannerLabel: { color: '#54655B', fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  syncBannerText: { color: '#173A2A', fontSize: 14, fontWeight: '700', marginTop: 3 },
  muted: { fontSize: 14, lineHeight: 20, color: '#6A776F' },
  back: { color: '#2E7D58', fontWeight: '700', fontSize: 16, marginBottom: 4 },
  card: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 16, borderWidth: 1, borderColor: '#DFE7E1', gap: 10 },
  comingSoonCard: { backgroundColor: '#FFFFFF', borderRadius: 24, padding: 28, borderWidth: 1, borderColor: '#DFE7E1', alignItems: 'center', gap: 12, marginTop: 16 },
  comingSoonIcon: { fontSize: 46, color: '#9AABA1' },
  taskCard: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 16, borderWidth: 1, borderColor: '#DFE7E1', flexDirection: 'row', alignItems: 'center', gap: 12 },
  lockedCard: { opacity: 0.7, backgroundColor: '#EEF1EF' },
  cardTitle: { fontSize: 17, fontWeight: '800', color: '#1D2A23' },
  listItem: { fontSize: 15, lineHeight: 23, color: '#405047' },
  chevron: { fontSize: 28, color: '#6A776F' },
  badgeSlot: { width: 66, height: 66, borderRadius: 20, borderWidth: 2, borderStyle: 'dashed', borderColor: '#BFCBC4', backgroundColor: '#EEF2EF', alignItems: 'center', justifyContent: 'center' },
  badgeUnlocked: { borderStyle: 'solid', borderColor: '#D09B2D', backgroundColor: '#FFF5D9' },
  badgeNewUser: { borderStyle: 'solid', borderColor: '#9FC8B1', backgroundColor: '#E5F2EA' },
  badgeIcon: { fontSize: 25, color: '#91A097' },
  badgeText: { fontSize: 10, fontWeight: '800', color: '#7D8A82', marginTop: 1 },
  badgeTextUnlocked: { color: '#8C6517' },
  featureCard: { borderRadius: 24, padding: 18, borderWidth: 1, gap: 10 },
  featureCardPrimary: { backgroundColor: '#E5F2EA', borderColor: '#B8D6C5' },
  featureCardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  featureIcon: { width: 78, height: 48, borderRadius: 16, backgroundColor: '#2E7D58', alignItems: 'center', justifyContent: 'center' },
  featureIconText: { color: '#FFFFFF', fontSize: 24, fontWeight: '900' },
  progressCircle: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#173A2A', alignItems: 'center', justifyContent: 'center' },
  progressCircleText: { color: '#FFFFFF', fontSize: 16, fontWeight: '900' },
  featureTitle: { fontSize: 22, fontWeight: '900', color: '#173A2A' },
  featureDescription: { fontSize: 14, color: '#506158' },
  openHint: { color: '#2E7D58', fontWeight: '800', textAlign: 'right', marginTop: 4 },
  featureGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  futureFeatureCard: { width: '48%', minHeight: 142, backgroundColor: '#FFFFFF', borderRadius: 18, padding: 14, borderWidth: 1, borderColor: '#DFE7E1' },
  futureIcon: { width: 34, height: 34, borderRadius: 11, backgroundColor: '#EEF2EF', alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  futureIconText: { color: '#688076', fontSize: 17, fontWeight: '900' },
  featureImageIcon: { width: 22, height: 22, resizeMode: 'contain' },
  featureImageIconLight: { width: 25, height: 25, resizeMode: 'contain', tintColor: '#FFFFFF' },
  futureFeatureTitle: { fontSize: 15, fontWeight: '800', color: '#1D2A23' },
  futureFeatureSubtitle: { fontSize: 12, lineHeight: 17, color: '#77837C', marginTop: 4 },
  comingSoonLabel: { fontSize: 9, letterSpacing: 0.8, fontWeight: '900', color: '#829087', marginTop: 10 },
  quickLinkLabel: { fontSize: 10, letterSpacing: 0.8, fontWeight: '900', color: '#2E7D58', marginTop: 10 },
  progressTrack: { height: 10, backgroundColor: '#D8E1DB', borderRadius: 999, overflow: 'hidden', marginTop: 8 },
  progressFill: { height: '100%', backgroundColor: '#2E7D58', borderRadius: 999 },
  metricRowCompact: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 4 },
  metric: { flex: 1 },
  metricValue: { fontSize: 24, fontWeight: '800', color: '#173A2A' },
  metricLabel: { fontSize: 12, color: '#5C6B62', marginTop: 2 },
  button: { backgroundColor: '#2E7D58', minHeight: 48, paddingVertical: 14, paddingHorizontal: 18, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  buttonSecondary: { backgroundColor: '#E7ECE9' },
  buttonDisabled: { opacity: 0.45 },
  buttonPressed: { transform: [{ scale: 0.99 }], opacity: 0.9 },
  buttonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '800', textAlign: 'center' },
  buttonSecondaryText: { color: '#173A2A' },
  buttonRow: { flexDirection: 'row', gap: 10 },
  smallButton: { flex: 1, padding: 12, backgroundColor: '#EAF2ED', borderRadius: 12, alignItems: 'center', borderWidth: 2, borderColor: 'transparent' },
  smallButtonSelected: { backgroundColor: '#2E7D58', borderColor: '#173A2A' },
  smallButtonText: { color: '#173A2A', fontWeight: '700' },
  smallButtonTextSelected: { color: '#FFFFFF' },
  selectionFeedback: { fontSize: 13, fontWeight: '700', color: '#2E7D58' },
  label: { fontSize: 13, fontWeight: '700', color: '#405047', marginTop: 4 },
  input: { backgroundColor: '#F5F7F6', borderRadius: 12, paddingHorizontal: 13, paddingVertical: 12, borderWidth: 1, borderColor: '#DCE4DE', fontSize: 16 },
  inputDisabled: { color: '#6A776F', backgroundColor: '#E9EEEB' },
  multilineInput: { minHeight: 88 },
  option: { padding: 13, borderRadius: 12, borderWidth: 1, borderColor: '#DCE4DE', backgroundColor: '#FAFBFA' },
  optionSelected: { borderColor: '#2E7D58', backgroundColor: '#E5F2EA' },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  tag: { fontSize: 12, fontWeight: '700', color: '#285E45', backgroundColor: '#E5F2EA', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 999, textTransform: 'capitalize' },
  tagWarning: { color: '#7A5200', backgroundColor: '#FFF0C7' },
  tagInProgress: { color: '#725100', backgroundColor: '#FFE7A3' },
  tagDanger: { color: '#8A2525', backgroundColor: '#FCE1E1' },
  screenHeader: { paddingTop: Platform.OS === 'android' ? 8 : 0 },
  carouselPage: { flex: 1, backgroundColor: '#F4F7F5' },
  carouselHeader: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 12, backgroundColor: '#FFFFFF', borderBottomWidth: 1, borderBottomColor: '#DFE7E1' },
  carouselEyebrow: { color: '#2E7D58', fontWeight: '900', letterSpacing: 1, fontSize: 10, marginTop: 2 },
  carouselTitle: { color: '#17211C', fontSize: 22, fontWeight: '900', marginTop: 3 },
  stepDots: { flexDirection: 'row', marginTop: 14, gap: 5 },
  stepDotItem: { flex: 1, gap: 5 },
  stepDot: { height: 5, borderRadius: 4, backgroundColor: '#DCE4DE' },
  stepDotActive: { backgroundColor: '#2E7D58' },
  stepDotDone: { backgroundColor: '#8EC0A5' },
  stepDotLabel: { color: '#839087', fontSize: 9, fontWeight: '700' },
  stepDotLabelActive: { color: '#2E7D58' },
  slide: { padding: 20, gap: 14, paddingBottom: 28 },
  slideKicker: { color: '#2E7D58', fontSize: 11, fontWeight: '900', letterSpacing: 1.2 },
  slideHeading: { color: '#17211C', fontSize: 25, lineHeight: 31, fontWeight: '900' },
  targetCard: { backgroundColor: '#173A2A', borderRadius: 18, padding: 18, gap: 6 },
  targetLabel: { color: '#A8D9BE', fontSize: 10, fontWeight: '900', letterSpacing: 1.1 },
  targetText: { color: '#FFFFFF', fontSize: 17, lineHeight: 24, fontWeight: '700' },
  viabilityNote: { backgroundColor: '#FFFFFF', borderRadius: 16, padding: 15, borderWidth: 1, borderColor: '#DFE7E1', gap: 4 },
  viabilityNoteTitle: { color: '#1D2A23', fontSize: 15, fontWeight: '800' },
  fieldHelp: { color: '#6A776F', fontSize: 13, lineHeight: 19, marginTop: -7 },
  requirementCheck: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#F0F3F1', borderRadius: 13, padding: 12, gap: 9 },
  requirementCheckMet: { backgroundColor: '#E5F2EA' },
  requirementCheckIcon: { color: '#2E7D58', fontSize: 18, fontWeight: '900' },
  requirementCheckText: { flex: 1, color: '#405047', fontSize: 13, fontWeight: '700' },
  quizOption: { flexDirection: 'row', alignItems: 'center', padding: 14, backgroundColor: '#FFFFFF', borderWidth: 2, borderColor: '#DFE7E1', borderRadius: 15, gap: 12 },
  quizOptionSelected: { borderColor: '#2E7D58', backgroundColor: '#EFF8F2' },
  quizOptionCorrect: { borderColor: '#2E7D58', backgroundColor: '#DDF2E5' },
  quizOptionIncorrect: { borderColor: '#B54444', backgroundColor: '#FCE7E7' },
  quizOptionMarker: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E5F2EA' },
  quizOptionMarkerText: { color: '#2E7D58', fontWeight: '900', textAlign: 'center', lineHeight: 18 },
  quizOptionText: { flex: 1, color: '#1D2A23', fontSize: 14, lineHeight: 20, fontWeight: '600' },
  feedbackCard: { borderRadius: 15, padding: 14, gap: 4, borderWidth: 1 },
  feedbackCorrect: { backgroundColor: '#DDF2E5', borderColor: '#94C7A9' },
  feedbackIncorrect: { backgroundColor: '#FFF0E4', borderColor: '#E8B98F' },
  feedbackTitle: { color: '#173A2A', fontWeight: '900', fontSize: 15 },
  feedbackText: { color: '#405047', lineHeight: 20 },
  reviewRow: { flexDirection: 'row', alignItems: 'center', padding: 14, borderRadius: 14, backgroundColor: '#F0F3F1', gap: 10 },
  reviewRowMet: { backgroundColor: '#E5F2EA' },
  reviewRowIcon: { color: '#2E7D58', fontWeight: '900', fontSize: 18 },
  reviewRowText: { flex: 1, color: '#405047', fontWeight: '700', lineHeight: 20 },
  syncSummary: { backgroundColor: '#FFFFFF', borderRadius: 14, padding: 13, borderWidth: 1, borderColor: '#DFE7E1' },
  reviewDisclaimer: { color: '#6A776F', fontSize: 13, lineHeight: 19 },
  carouselControls: { height: 54, paddingHorizontal: 20, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FFFFFF', borderTopWidth: 1, borderTopColor: '#DFE7E1' },
  carouselControlText: { color: '#2E7D58', fontWeight: '800' },
  carouselControlDisabled: { color: '#B9C2BC' },
  carouselControlCenter: { color: '#536159', fontSize: 12, fontWeight: '800' },
  tierOverviewCard: { backgroundColor: '#FFFFFF', borderRadius: 20, padding: 17, borderWidth: 1, borderColor: '#DFE7E1', gap: 10 },
  tierOverviewLocked: { backgroundColor: '#EEF1EF', opacity: 0.72 },
  tierOverviewHeader: { flexDirection: 'row', alignItems: 'center', gap: 11 },
  tierNumberBadge: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#E5F2EA', alignItems: 'center', justifyContent: 'center' },
  tierNumberBadgeComplete: { backgroundColor: '#2E7D58' },
  tierNumberBadgeText: { color: '#173A2A', fontWeight: '900', fontSize: 17 },
  tierOverviewCopy: { flex: 1 },
  tierOverviewLabel: { color: '#2E7D58', fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  tierOverviewTitle: { color: '#1D2A23', fontSize: 17, fontWeight: '900', marginTop: 2 },
  tierOverviewStatus: { color: '#2E7D58', fontWeight: '900' },
  tierOverviewCount: { color: '#6A776F', fontSize: 12, fontWeight: '700' },
  lockRequirement: { color: '#6A776F', fontSize: 13, fontWeight: '700', marginLeft: 53 },
  taskStateIcon: { width: 36, height: 36, borderRadius: 18, backgroundColor: '#EEF2EF', alignItems: 'center', justifyContent: 'center' },
  taskStateIconComplete: { backgroundColor: '#2E7D58' },
  taskStateIconText: { color: '#607068', fontSize: 18, fontWeight: '900' },
  taskStateIconTextComplete: { color: '#FFFFFF' },
  entryEditor: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 15, borderWidth: 1, borderColor: '#DFE7E1', gap: 10 },
  categoryChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  categoryChip: { borderRadius: 999, backgroundColor: '#EEF2EF', paddingHorizontal: 11, paddingVertical: 8, borderWidth: 1, borderColor: '#DFE7E1' },
  categoryChipSelected: { backgroundColor: '#2E7D58', borderColor: '#2E7D58' },
  categoryChipText: { color: '#536159', fontSize: 12, fontWeight: '700' },
  categoryChipTextSelected: { color: '#FFFFFF' },
  entryActions: { gap: 8 },
  emptyInventory: { backgroundColor: '#FFFFFF', borderRadius: 15, padding: 16, borderWidth: 1, borderStyle: 'dashed', borderColor: '#C8D2CB' },
  inventoryList: { gap: 9 },
  inventoryItem: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', padding: 13, borderRadius: 14, borderWidth: 1, borderColor: '#DFE7E1', gap: 10 },
  inventoryItemName: { color: '#1D2A23', fontSize: 15, fontWeight: '800' },
  inventoryItemMeta: { color: '#6A776F', fontSize: 12, lineHeight: 18, marginTop: 3 },
  inventoryItemActions: { alignItems: 'flex-end', gap: 7 },
  inventoryAction: { color: '#2E7D58', fontWeight: '800', fontSize: 12 },
  inventoryDelete: { color: '#A33D3D', fontWeight: '800', fontSize: 12 },
  requirementPanel: { backgroundColor: '#FFF5D9', borderRadius: 14, padding: 13, borderWidth: 1, borderColor: '#E8CA79', gap: 4 },
  requirementPanelMet: { backgroundColor: '#E5F2EA', borderColor: '#B8D6C5' },
  requirementPanelTitle: { color: '#173A2A', fontWeight: '900' },
  requirementPanelText: { color: '#536159', fontSize: 12, lineHeight: 18 },
  completedBanner: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#E5F2EA', borderRadius: 18, padding: 16, gap: 12 },
  completedBannerIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: '#2E7D58', color: '#FFFFFF', textAlign: 'center', textAlignVertical: 'center', lineHeight: 38, fontSize: 20, fontWeight: '900' },
  completedBannerTitle: { color: '#173A2A', fontSize: 16, fontWeight: '900' },
  sectionTitle: { color: '#1D2A23', fontSize: 19, fontWeight: '900', marginTop: 6 },
  quizQuestion: { color: '#17211C', fontSize: 22, lineHeight: 29, fontWeight: '900', marginTop: 8 },
  quizScoreCard: { backgroundColor: '#FFF0E4', borderRadius: 22, padding: 22, alignItems: 'center', borderWidth: 1, borderColor: '#E8B98F' },
  quizScoreCardPassed: { backgroundColor: '#E5F2EA', borderColor: '#9FC8B1' },
  quizScore: { color: '#173A2A', fontSize: 46, fontWeight: '900' },
  quizPercentage: { color: '#2E7D58', fontSize: 20, fontWeight: '900', marginBottom: 5 },
  answerReview: { flexDirection: 'row', backgroundColor: '#FFFFFF', borderRadius: 15, padding: 14, borderWidth: 1, borderColor: '#DFE7E1', gap: 10 },
  answerReviewState: { color: '#2E7D58', fontSize: 20, fontWeight: '900' },
  answerReviewQuestion: { color: '#1D2A23', fontWeight: '800', lineHeight: 20 },
  answerReviewSelected: { color: '#9A3D3D', fontSize: 12, marginTop: 5 },
  answerReviewExplanation: { color: '#637168', fontSize: 12, lineHeight: 18, marginTop: 5 },
  historyCard: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FFFFFF', borderRadius: 15, padding: 15, borderWidth: 1, borderColor: '#DFE7E1' },
  historyScore: { color: '#173A2A', fontSize: 20, fontWeight: '900', textAlign: 'right' },
  historyStatus: { color: '#9A3D3D', fontSize: 11, fontWeight: '800' },
  historyPassed: { color: '#2E7D58' },
  permissionCard: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 16, borderWidth: 1, borderColor: '#DFE7E1', gap: 11 },
  expiryCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF5D9', borderRadius: 15, padding: 14, borderWidth: 1, borderColor: '#E8CA79', gap: 10 },
  expiryCardExpired: { backgroundColor: '#FCE1E1', borderColor: '#E7AAAA' },
  expiryStatus: { color: '#725100', fontSize: 11, fontWeight: '900' },
  expiryStatusExpired: { color: '#9A3D3D' },
  resourceCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#DFE7E1', gap: 12 },
  resourceIcon: { width: 40, height: 40, borderRadius: 13, backgroundColor: '#E5F2EA', alignItems: 'center', justifyContent: 'center' },
  resourceIconText: { color: '#2E7D58', fontWeight: '900', fontSize: 16 },
  quizEntryCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#173A2A', borderRadius: 20, padding: 17, gap: 13 },
  quizEntryIcon: { width: 46, height: 46, borderRadius: 15, backgroundColor: '#2E7D58', alignItems: 'center', justifyContent: 'center' },
  quizEntryIconText: { color: '#FFFFFF', fontSize: 23, fontWeight: '900' },
  quizEntryLabel: { color: '#A8D9BE', fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  quizEntryTitle: { color: '#FFFFFF', fontSize: 17, fontWeight: '900', marginTop: 2 },
  quizEntryText: { color: '#C8DDD1', fontSize: 12, lineHeight: 18, marginTop: 3 },
  mixedQuizCard: { backgroundColor: '#E5F2EA', borderRadius: 20, padding: 18, borderWidth: 1, borderColor: '#9FC8B1' },
  mixedQuizLabel: { color: '#2E7D58', fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  mixedQuizTitle: { color: '#173A2A', fontSize: 20, fontWeight: '900', marginTop: 5 },
  mixedQuizText: { color: '#536159', lineHeight: 20, marginTop: 4 },
  mixedQuizHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  realtimeAlertCard: { backgroundColor: '#EEF2EF', borderRadius: 18, padding: 16, borderWidth: 1, borderStyle: 'dashed', borderColor: '#AAB7AF', gap: 5 },
  realtimeAlertLabel: { color: '#6A776F', fontSize: 10, fontWeight: '900', letterSpacing: 1 },
  segmentedControl: { flexDirection: 'row', backgroundColor: '#E5EAE7', padding: 4, borderRadius: 15, gap: 3 },
  segmentButton: { flex: 1, minHeight: 43, borderRadius: 11, paddingHorizontal: 6, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 5 },
  segmentButtonActive: { backgroundColor: '#FFFFFF' },
  segmentText: { color: '#65736B', fontSize: 12, fontWeight: '800', textAlign: 'center' },
  segmentTextActive: { color: '#2E7D58' },
  segmentBadge: { minWidth: 18, height: 18, borderRadius: 9, paddingHorizontal: 4, backgroundColor: '#B54444', alignItems: 'center', justifyContent: 'center' },
  segmentBadgeText: { color: '#FFFFFF', fontSize: 10, fontWeight: '900' },
  profileSection: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 16, borderWidth: 1, borderColor: '#DFE7E1', gap: 12 },
  contactCard: { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: '#F5F7F6', borderRadius: 14, padding: 13, borderWidth: 1, borderColor: '#DFE7E1', gap: 12 },
  alertFeedHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  liveBadge: { backgroundColor: '#173A2A', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6 },
  liveBadgeText: { color: '#FFFFFF', fontSize: 10, fontWeight: '900', letterSpacing: 0.8 },
  inlineWarning: { color: '#725100', backgroundColor: '#FFF5D9', borderRadius: 12, padding: 12, lineHeight: 19 },
  hazardCard: { flexDirection: 'row', overflow: 'hidden', backgroundColor: '#FFFFFF', borderRadius: 17, borderWidth: 1, borderColor: '#DFE7E1', paddingVertical: 14, paddingRight: 14, gap: 13 },
  alertLevelBar: { width: 7, borderRadius: 5, backgroundColor: '#4E9B68' },
  alertLevelOrange: { backgroundColor: '#E38A2D' },
  alertLevelRed: { backgroundColor: '#C94848' },
  hazardMeta: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 5 },
  hazardType: { color: '#536159', fontSize: 11, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 0.7 },
  alertLevelText: { color: '#2E7D58', backgroundColor: '#E5F2EA', borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4, fontSize: 10, fontWeight: '900' },
  alertLevelTextOrange: { color: '#89500E', backgroundColor: '#FFF0D8' },
  alertLevelTextRed: { color: '#982D2D', backgroundColor: '#FCE1E1' },
  openReport: { color: '#2E7D58', fontSize: 12, fontWeight: '800', marginTop: 8 },
  notice: { backgroundColor: '#EDF3EF', borderRadius: 14, borderWidth: 1, borderColor: '#CEDBD3', padding: 13 },
  noticeText: { color: '#536159', fontSize: 12, lineHeight: 18 },
  profileHero: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#173A2A', borderRadius: 22, padding: 18, gap: 13 },
  avatar: { width: 58, height: 58, borderRadius: 20, backgroundColor: '#C9E7D6', alignItems: 'center', justifyContent: 'center' },
  avatarText: { color: '#173A2A', fontSize: 21, fontWeight: '900' },
  profilePhoto: { width: '100%', height: '100%', borderRadius: 20 },
  photoEditBadge: { position: 'absolute', right: -4, bottom: -4, width: 23, height: 23, borderRadius: 12, backgroundColor: '#F1B24A', borderWidth: 2, borderColor: '#173A2A', alignItems: 'center', justifyContent: 'center' },
  photoEditText: { color: '#173A2A', fontSize: 16, lineHeight: 18, fontWeight: '900' },
  changePhotoText: { color: '#F1D598', fontSize: 10, fontWeight: '700', marginTop: 5 },
  profileHeroName: { color: '#FFFFFF', fontSize: 20, fontWeight: '900' },
  profileHeroEmail: { color: '#BFD5C8', fontSize: 12, marginTop: 4 },
  profilePercent: { width: 48, height: 48, borderRadius: 24, backgroundColor: '#2E7D58', alignItems: 'center', justifyContent: 'center' },
  profilePercentText: { color: '#FFFFFF', fontSize: 13, fontWeight: '900' },
  profileCompletion: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 15, borderWidth: 1, borderColor: '#DFE7E1', gap: 8 },
  profileCompletionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  profileCompletionLabel: { color: '#2E7D58', fontSize: 12, fontWeight: '800' },
  profileTabs: { flexDirection: 'row', backgroundColor: '#E5EAE7', borderRadius: 15, padding: 4, gap: 3 },
  profileTab: { flex: 1, minHeight: 42, borderRadius: 11, alignItems: 'center', justifyContent: 'center' },
  profileTabActive: { backgroundColor: '#FFFFFF' },
  profileTabText: { color: '#65736B', fontSize: 12, fontWeight: '800' },
  profileTabTextActive: { color: '#2E7D58' },
  sectionHeading: { flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 2 },
  sectionHeadingIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#E5F2EA', alignItems: 'center', justifyContent: 'center' },
  sectionHeadingIconText: { color: '#2E7D58', fontSize: 12, fontWeight: '900' },
  contactAvatar: { width: 40, height: 40, borderRadius: 13, backgroundColor: '#DDECE3', alignItems: 'center', justifyContent: 'center' },
  contactAvatarText: { color: '#2E7D58', fontSize: 16, fontWeight: '900' },
  contactRelationship: { color: '#2E7D58', fontSize: 12, fontWeight: '800', marginTop: 2 },
  contactActions: { alignItems: 'flex-end', gap: 9 },
  contactEditor: { backgroundColor: '#F5F7F6', borderRadius: 16, padding: 14, gap: 11, borderWidth: 1, borderColor: '#DFE7E1' },
  accountActions: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 16, borderWidth: 1, borderColor: '#DFE7E1', gap: 12 },
  cacheStatus: { color: '#6A776F', textAlign: 'center', fontSize: 11 },
  iconAttribution: { color: '#8B9991', textAlign: 'center', fontSize: 10 },
  proximityCard: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 15, borderWidth: 1, borderColor: '#DFE7E1', gap: 12 },
  radiusRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  radiusChip: { borderRadius: 999, paddingHorizontal: 11, paddingVertical: 8, backgroundColor: '#EEF2EF', borderWidth: 1, borderColor: '#D8E1DB' },
  radiusChipActive: { backgroundColor: '#2E7D58', borderColor: '#2E7D58' },
  radiusChipText: { color: '#536159', fontSize: 11, fontWeight: '800' },
  radiusChipTextActive: { color: '#FFFFFF' },
  homeRewardCard: { backgroundColor: '#173A2A', borderRadius: 18, padding: 15, gap: 8 },
  homeRewardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  homeRewardRank: { color: '#FFFFFF', fontSize: 16, fontWeight: '900' },
  homeRewardPoints: { color: '#BFD5C8', fontSize: 12, marginTop: 3 },
  homeRewardChevron: { color: '#FFFFFF', fontSize: 28 },
  homeRewardHint: { color: '#C8DDD1', fontSize: 11 },
  rewardHero: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#173A2A', borderRadius: 22, padding: 18, gap: 15 },
  rewardLevelOrb: { width: 70, height: 70, borderRadius: 24, backgroundColor: '#D5AC52', alignItems: 'center', justifyContent: 'center' },
  rewardLevelNumber: { color: '#173A2A', fontSize: 28, fontWeight: '900' },
  rewardLevelLabel: { color: '#5D4616', fontSize: 8, fontWeight: '900', letterSpacing: 1 },
  rewardRank: { color: '#FFFFFF', fontSize: 20, fontWeight: '900' },
  rewardPoints: { color: '#BFD5C8', fontSize: 13, marginTop: 3 },
  rewardNext: { color: '#C8DDD1', fontSize: 11, marginTop: 6 },
  missionCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#DFE7E1', gap: 11 },
  missionCardDone: { backgroundColor: '#EAF5EE', borderColor: '#AFD1BC' },
  missionCheck: { width: 38, height: 38, borderRadius: 13, backgroundColor: '#E6ECE8', alignItems: 'center', justifyContent: 'center' },
  missionCheckDone: { backgroundColor: '#2E7D58' },
  missionCheckText: { color: '#FFFFFF', fontSize: 17, fontWeight: '900' },
  missionCount: { color: '#2E7D58', fontSize: 12, fontWeight: '900' },
  rewardBadgeCount: { color: '#2E7D58', fontSize: 12, fontWeight: '800' },
  rewardFilter: { flexDirection: 'row', alignSelf: 'flex-start', backgroundColor: '#E5EAE7', borderRadius: 12, padding: 3 },
  rewardFilterButton: { paddingHorizontal: 18, paddingVertical: 8, borderRadius: 9 },
  rewardFilterActive: { backgroundColor: '#FFFFFF' },
  rewardFilterText: { color: '#65736B', fontSize: 12, fontWeight: '800' },
  rewardFilterTextActive: { color: '#2E7D58' },
  badgeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  rewardBadge: { width: '48%', minHeight: 196, backgroundColor: '#EEF1EF', borderRadius: 18, padding: 14, borderWidth: 1, borderColor: '#DCE4DE', alignItems: 'center' },
  rewardBadgeEarned: { backgroundColor: '#FFF8E8', borderColor: '#E2C479' },
  rewardBadgeIcon: { width: 54, height: 54, borderRadius: 18, backgroundColor: '#DCE3DF', alignItems: 'center', justifyContent: 'center', marginBottom: 9 },
  rewardBadgeIconEarned: { backgroundColor: '#D5AC52' },
  rewardBadgeIconText: { color: '#77837C', fontSize: 18, fontWeight: '900' },
  rewardBadgeIconTextEarned: { color: '#49350C' },
  rewardBadgeTitle: { color: '#1D2A23', fontSize: 14, fontWeight: '900', textAlign: 'center' },
  rewardBadgeDescription: { color: '#6A776F', fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: 5, flex: 1 },
  rewardBadgeProgress: { color: '#68756D', backgroundColor: '#DCE3DF', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5, fontSize: 10, fontWeight: '900', marginTop: 8 },
  rewardBadgeProgressEarned: { color: '#715214', backgroundColor: '#F5DEA8' },
  rewardEvent: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 14, padding: 13, borderWidth: 1, borderColor: '#DFE7E1', gap: 10 },
  rewardEventDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#D5AC52' },
  rewardEventPoints: { color: '#2E7D58', fontSize: 15, fontWeight: '900' },
  masteryPanel: { backgroundColor: '#FFFFFF', borderRadius: 18, borderWidth: 1, borderColor: '#DFE7E1', overflow: 'hidden' },
  masteryRow: { flexDirection: 'row', alignItems: 'center', padding: 13, borderBottomWidth: 1, borderBottomColor: '#EEF2EF', gap: 10 },
  masteryTitle: { color: '#1D2A23', fontSize: 14, fontWeight: '900', textTransform: 'capitalize' },
  masteryLevel: { color: '#65736B', backgroundColor: '#EEF2EF', borderRadius: 999, paddingHorizontal: 9, paddingVertical: 5, fontSize: 10, fontWeight: '900' },
  masteryLevelDone: { color: '#725100', backgroundColor: '#FFE7A3' },
  backdrop: { ...StyleSheet.absoluteFillObject, overflow: 'hidden' },
  backdropBlob: { position: 'absolute', width: 250, height: 250, borderRadius: 125, opacity: 0.42 },
  backdropBlobTop: { top: -125, right: -100 },
  backdropBlobBottom: { bottom: 40, left: -165, width: 290, height: 290, borderRadius: 145, opacity: 0.23 },
  backdropBlob_green: { backgroundColor: '#CFE8D9' },
  backdropBlob_orange: { backgroundColor: '#F8D7A4' },
  backdropBlob_blue: { backgroundColor: '#BFDDED' },
  backdropBlob_red: { backgroundColor: '#F4C7C0' },
  backdropBlob_purple: { backgroundColor: '#DCCDEB' },
  backdropDotGrid: { position: 'absolute', top: 115, left: 12, width: 70, flexDirection: 'row', flexWrap: 'wrap', gap: 12, opacity: 0.35 },
  backdropDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: '#809087' },
  learningHero: { minHeight: 190, flexDirection: 'row', alignItems: 'center', overflow: 'hidden', backgroundColor: '#1E5E78', borderRadius: 26, padding: 20, gap: 12 },
  learningHeroEyebrow: { color: '#A9D9EA', fontSize: 10, fontWeight: '900', letterSpacing: 1.3 },
  learningHeroTitle: { color: '#FFFFFF', fontSize: 27, lineHeight: 32, fontWeight: '900', marginTop: 6 },
  learningHeroText: { color: '#D5ECF3', fontSize: 13, lineHeight: 19, marginTop: 8 },
  learningHeroArt: { width: 72, height: 112, borderRadius: 30, backgroundColor: '#F1B24A', alignItems: 'center', justifyContent: 'center', transform: [{ rotate: '7deg' }] },
  learningHeroArtText: { color: '#173A2A', fontSize: 52, fontWeight: '900', fontStyle: 'italic' },
  quizEntryArrow: { color: '#FFFFFF', fontSize: 29, fontWeight: '300' },
  sectionHeadingRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 10 },
  learningGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  learningCategoryCard: { width: '48%', minHeight: 205, borderRadius: 21, padding: 15, borderWidth: 1, borderColor: '#B9DCEB' },
  learningCardBlue: { backgroundColor: '#E2F3FA' },
  learningCardOrange: { backgroundColor: '#FFF0DA', borderColor: '#F2D19B' },
  learningCardPurple: { backgroundColor: '#F0E8F7', borderColor: '#D8C2E8' },
  learningCardYellow: { backgroundColor: '#FFF8CF', borderColor: '#E8DA8C' },
  learningCategoryIcon: { width: 48, height: 48, borderRadius: 16, backgroundColor: 'rgba(255,255,255,0.75)', alignItems: 'center', justifyContent: 'center' },
  learningCategoryImage: { width: 27, height: 27, resizeMode: 'contain' },
  learningCategoryTitle: { color: '#173A2A', fontSize: 16, fontWeight: '900', marginTop: 12 },
  learningCategoryDescription: { color: '#5B6C63', fontSize: 11, lineHeight: 16, marginTop: 5, flex: 1 },
  learningCategoryOpen: { color: '#1E6B83', fontSize: 11, fontWeight: '900', marginTop: 8 },
  learningSafetyNote: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF5D9', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#E8CA79', gap: 10 },
  learningSafetyIcon: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#F1B24A', color: '#173A2A', textAlign: 'center', lineHeight: 28, fontWeight: '900' },
  learningSafetyText: { flex: 1, color: '#6B5414', fontSize: 12, lineHeight: 18 },
  quizHero: { backgroundColor: '#5E3E7A', borderRadius: 24, padding: 20 },
  quizHeroKicker: { color: '#D8C1EA', fontSize: 10, fontWeight: '900', letterSpacing: 1.1 },
  quizHeroTitle: { color: '#FFFFFF', fontSize: 27, fontWeight: '900', marginTop: 6 },
  quizHeroText: { color: '#E9DCF2', fontSize: 13, lineHeight: 19, marginTop: 7 },
  mixedQuizFeature: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#173A2A', borderRadius: 21, padding: 16, gap: 13 },
  mixedQuizIconLarge: { width: 58, height: 58, borderRadius: 18, backgroundColor: '#F1B24A', alignItems: 'center', justifyContent: 'center' },
  mixedQuizImage: { width: 32, height: 32, resizeMode: 'contain' },
  mixedQuizFeatureTitle: { color: '#FFFFFF', fontSize: 17, fontWeight: '900', marginTop: 3 },
  mixedQuizFeatureText: { color: '#BDD5C8', fontSize: 11, lineHeight: 16, marginTop: 3 },
  quizCategoryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  quizCategoryTile: { width: '48%', minHeight: 178, borderRadius: 20, padding: 15, backgroundColor: '#E2F3FA', borderWidth: 1, borderColor: '#BDDDEB' },
  quizCategoryTileOrange: { backgroundColor: '#FFF0DA', borderColor: '#F0D09C' },
  quizCategoryTilePurple: { backgroundColor: '#F0E8F7', borderColor: '#D7C3E7' },
  quizCategoryImage: { width: 34, height: 34, resizeMode: 'contain' },
  quizCategoryTitle: { color: '#173A2A', fontSize: 15, fontWeight: '900', marginTop: 10 },
  quizCategoryMeta: { color: '#64756C', fontSize: 10, marginTop: 4 },
  quizCategoryCta: { marginTop: 'auto', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  quizCategoryCtaText: { color: '#2E7D58', fontSize: 12, fontWeight: '900' },
  quizCategoryCtaArrow: { color: '#2E7D58', fontSize: 21 },
  categoryHero: { alignItems: 'flex-start', backgroundColor: '#DFF1F7', borderRadius: 25, padding: 20, borderWidth: 1, borderColor: '#B9DCEB' },
  categoryHeroIcon: { width: 64, height: 64, borderRadius: 21, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', marginBottom: 13 },
  categoryHeroImage: { width: 38, height: 38, resizeMode: 'contain' },
  categoryHeroKicker: { color: '#1E6B83', fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  categoryHeroTitle: { color: '#173A2A', fontSize: 28, fontWeight: '900', marginTop: 5 },
  categoryHeroText: { color: '#536A60', lineHeight: 21, marginTop: 7 },
  categoryHeroMeta: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 14 },
  categoryMetaPill: { color: '#1E5E78', backgroundColor: '#FFFFFF', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, fontSize: 10, fontWeight: '800' },
  categoryQuizBanner: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#5E3E7A', borderRadius: 18, padding: 16 },
  categoryQuizKicker: { color: '#DCC9EA', fontSize: 9, fontWeight: '900', letterSpacing: 1 },
  categoryQuizTitle: { color: '#FFFFFF', fontSize: 16, fontWeight: '900', marginTop: 3 },
  categoryQuizText: { color: '#E7DDF0', fontSize: 11, marginTop: 3 },
  categoryQuizArrow: { color: '#FFFFFF', fontSize: 30 },
  articlePreviewCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 18, padding: 15, borderWidth: 1, borderColor: '#E0DED7', gap: 12 },
  articlePreviewNumber: { width: 42, height: 54, borderRadius: 14, backgroundColor: '#FFF0DA', alignItems: 'center', justifyContent: 'center' },
  articlePreviewNumberText: { color: '#9B6425', fontSize: 15, fontWeight: '900' },
  articlePreviewLabel: { color: '#2E7D58', fontSize: 9, fontWeight: '900', letterSpacing: 1 },
  articlePreviewTitle: { color: '#1D2A23', fontSize: 16, fontWeight: '900', marginTop: 3 },
  articlePreviewSummary: { color: '#6A776F', fontSize: 12, lineHeight: 17, marginTop: 4 },
  articlePage: { padding: 20, gap: 16, paddingBottom: 28 },
  articleHero: { backgroundColor: '#1E5E78', borderRadius: 25, padding: 21 },
  articleHeroKicker: { color: '#A9D9EA', fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  articleHeroTitle: { color: '#FFFFFF', fontSize: 28, lineHeight: 34, fontWeight: '900', marginTop: 7 },
  articleHeroSummary: { color: '#D5ECF3', fontSize: 14, lineHeight: 21, marginTop: 9 },
  articleReadPill: { alignSelf: 'flex-start', backgroundColor: '#F1B24A', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 6, marginTop: 15 },
  articleReadPillText: { color: '#173A2A', fontSize: 10, fontWeight: '900' },
  articleSectionHeader: { marginTop: 3 },
  articleSectionKicker: { color: '#2E7D58', fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  articleSectionTitle: { color: '#17211C', fontSize: 21, fontWeight: '900', marginTop: 4 },
  guidanceStep: { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: '#FFFFFF', borderRadius: 17, padding: 15, borderWidth: 1, borderColor: '#DCE7E0', gap: 12 },
  guidanceStepAlt: { backgroundColor: '#FFF7E8', borderColor: '#ECD6AE' },
  guidanceStepNumber: { width: 32, height: 32, borderRadius: 11, backgroundColor: '#2E7D58', alignItems: 'center', justifyContent: 'center' },
  guidanceStepNumberAlt: { backgroundColor: '#D98A37' },
  guidanceStepNumberText: { color: '#FFFFFF', fontSize: 13, fontWeight: '900' },
  guidanceStepText: { flex: 1, color: '#33443B', fontSize: 15, lineHeight: 22, fontWeight: '600' },
  articleWarning: { flexDirection: 'row', backgroundColor: '#FBE6E1', borderRadius: 18, padding: 15, borderWidth: 1, borderColor: '#EABCB2', gap: 11 },
  articleWarningIcon: { width: 34, height: 34, borderRadius: 12, backgroundColor: '#C95345', alignItems: 'center', justifyContent: 'center' },
  articleWarningIconText: { color: '#FFFFFF', fontSize: 17, fontWeight: '900' },
  articleWarningTitle: { color: '#8B342C', fontSize: 14, fontWeight: '900' },
  articleWarningText: { color: '#744E49', fontSize: 12, lineHeight: 18, marginTop: 3 },
  articleSource: { backgroundColor: '#EEE8F4', borderRadius: 16, padding: 14, borderWidth: 1, borderColor: '#D8C8E5' },
  articleSourceKicker: { color: '#684985', fontSize: 9, fontWeight: '900', letterSpacing: 1 },
  articleSourceText: { color: '#4F405B', lineHeight: 19, marginTop: 5 },
  articleSourceDate: { color: '#7D6D87', fontSize: 11, marginTop: 4 },
  kitHero: { backgroundColor: '#8B5527', borderRadius: 26, padding: 20 },
  kitHeroEyebrow: { color: '#F7D2A5', fontSize: 10, fontWeight: '900', letterSpacing: 1.2 },
  kitHeroTitle: { color: '#FFFFFF', fontSize: 27, lineHeight: 33, fontWeight: '900', marginTop: 7 },
  kitHeroText: { color: '#F6E3CF', fontSize: 13, lineHeight: 19, marginTop: 8 },
  kitHeroStats: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.12)', borderRadius: 16, padding: 13, marginTop: 17 },
  kitHeroStatValue: { color: '#FFFFFF', fontSize: 19, fontWeight: '900', textAlign: 'center' },
  kitHeroStatLabel: { color: '#F6E3CF', fontSize: 9, marginTop: 2, textAlign: 'center' },
  kitHeroStatDivider: { width: 1, height: 31, backgroundColor: 'rgba(255,255,255,0.28)' },
  tierOverviewCard1: { backgroundColor: '#E6F3EB', borderColor: '#B9DCC7' },
  tierOverviewCard2: { backgroundColor: '#E6F2F8', borderColor: '#BBD8E6' },
  tierOverviewCard3: { backgroundColor: '#F0E8F5', borderColor: '#D5C1E1' },
});

export default styles;
